# Generated by Django 5.2 on 2025-06-15 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dataset_predictionresult_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
