# Generated by Django 5.2 on 2025-06-13 06:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_prediction_result_id_trend_prediction_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='model_performance',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 6, 22, 59, 768794, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('total_rows', models.IntegerField()),
                ('total_sectors', models.IntegerField()),
                ('year_min', models.IntegerField()),
                ('year_max', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='dataset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.dataset'),
            preserve_default=False,
        ),
    ]
