# Generated by Django 5.2 on 2025-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_predictionresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='category',
            field=models.CharField(choices=[('least_crowded', 'Least Crowded'), ('revenue', 'Revenue'), ('growth_rate', 'Growth Rate')], default='least_crowded', max_length=15),
            preserve_default=False,
        ),
    ]
